import { useEffect, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { Card } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { FileDown } from "lucide-react";

const Exports = () => {
  const [exports, setExports] = useState<any[]>([]);

  useEffect(() => {
    supabase.from("campaign_exports").select("*").order("exported_at", { ascending: false }).limit(50)
      .then(({ data }) => setExports(data || []));
  }, []);

  return (
    <div className="space-y-6">
      <div>
        <p className="text-sm text-muted-foreground font-medium uppercase tracking-wider">History</p>
        <h1 className="font-display text-3xl font-bold mt-1">Exports</h1>
        <p className="text-muted-foreground mt-1">Every CSV download generated by the team.</p>
      </div>
      <Card className="overflow-hidden">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>File</TableHead>
              <TableHead className="text-right">Members</TableHead>
              <TableHead>Exported at</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {exports.length === 0 ? (
              <TableRow><TableCell colSpan={3} className="py-12 text-center text-muted-foreground">No exports yet.</TableCell></TableRow>
            ) : exports.map((e) => (
              <TableRow key={e.id}>
                <TableCell className="font-mono text-sm flex items-center gap-2"><FileDown className="h-4 w-4 text-primary" />{e.file_reference || "—"}</TableCell>
                <TableCell className="text-right tabular-nums">{e.member_count}</TableCell>
                <TableCell className="text-sm">{new Date(e.exported_at).toLocaleString()}</TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </Card>
    </div>
  );
};

export default Exports;
